import React, { useEffect, useState } from 'react';
import { Activity, Search, UserPlus, Users, Zap } from 'lucide-react';

type SearchResult = { id: string; displayName: string | null; username: string | null; profileImageUrl: string | null; avatarStyle: string; level: number; streakDays: number; online: boolean };

export default function Social() {
  const [section, setSection] = useState<'friends' | 'activity'>('friends');
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<SearchResult[]>([]);
  const [loading, setLoading] = useState(false);
  useEffect(() => { const term = query.trim(); if (term.length < 2) { setResults([]); return; } const timer = window.setTimeout(async () => { setLoading(true); try { const response = await fetch(`/api/social/search?q=${encodeURIComponent(term)}`, { credentials: 'include' }); setResults(response.ok ? await response.json() as SearchResult[] : []); } finally { setLoading(false); } }, 250); return () => window.clearTimeout(timer); }, [query]);
  return <div className="space-y-5"><section className="bento-card p-5 sm:p-6"><div className="flex items-center gap-2 text-xs font-black uppercase text-primary"><Users className="h-4 w-4" /> Social</div><h1 className="tech-title mt-2 text-3xl sm:text-5xl">Your circle</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Connect around progress without exposing private task data.</p></section><section className="bento-card overflow-hidden"><div className="flex gap-2 border-b border-border p-3"><button onClick={() => setSection('friends')} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${section === 'friends' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`}><Users className="h-4 w-4" />Friends</button><button onClick={() => setSection('activity')} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${section === 'activity' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`}><Activity className="h-4 w-4" />Activity</button></div>{section === 'friends' ? <div className="p-5"><label className="flex items-center gap-2 rounded-xl border border-border bg-muted/40 px-3 py-2"><Search className="h-4 w-4 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by display name or username" className="min-w-0 flex-1 bg-transparent text-sm outline-none" /></label><div className="mt-4 space-y-2">{loading && <p className="p-4 text-center text-sm text-muted-foreground">Searching profiles...</p>}{results.map((person) => <div key={person.id} className="flex items-center gap-3 rounded-xl border border-border p-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground font-black">{person.displayName?.[0]?.toUpperCase() ?? '?'}</div><div className="min-w-0 flex-1"><p className="font-bold">{person.displayName ?? 'Velocity member'}</p><p className="text-xs text-muted-foreground">{person.username ? `@${person.username}` : 'Velocity member'} · Level {person.level} · {person.streakDays} day streak</p></div><button className="rounded-lg border border-primary/40 px-3 py-2 text-xs font-black text-primary"><UserPlus className="mr-1 inline h-3.5 w-3.5" /> Add</button></div>)}{query.trim().length >= 2 && !loading && results.length === 0 && <p className="p-6 text-center text-sm text-muted-foreground">No public profiles matched that search.</p>}</div></div> : <div className="p-10 text-center"><Activity className="mx-auto h-7 w-7 text-primary" /><p className="mt-3 font-bold">Friends-only activity</p><p className="mt-1 text-sm text-muted-foreground">Milestones, streaks, focus goals, and weekly challenges will appear here as you connect.</p></div>}</section></div>;
}
