import React, { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Archive, BookOpen, Brain, CheckCircle2, Circle, Clock, Code2, Droplets, Dumbbell, Heart, Music, Pause, Play, Plus, Repeat, Target, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { localDateKey } from '@/lib/localDate';

type Habit = { id: number; title: string; daysOfWeek: number[]; reminderTime: string | null; icon: string; vpReward: number; status: 'active' | 'paused' | 'archived'; completedToday: boolean; recentCompletions: string[] };
const weekdays = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
const iconMap = { target: Target, book: BookOpen, brain: Brain, heart: Heart, run: Dumbbell, water: Droplets, code: Code2, music: Music };

async function request<T>(path: string, options?: RequestInit) { const response = await fetch(path, { credentials: 'include', ...options, headers: options?.body ? { 'Content-Type': 'application/json' } : undefined }); if (!response.ok) { const data = await response.json().catch(() => ({})) as { error?: string }; throw new Error(data.error || 'Request failed'); } return response.status === 204 ? null as T : await response.json() as T; }

export function DailyChecklist() {
  const [habits, setHabits] = useState<Habit[]>([]);
  const [adding, setAdding] = useState(false);
  const [showArchived, setShowArchived] = useState(false);
  const [title, setTitle] = useState('');
  const [days, setDays] = useState([1,2,3,4,5]);
  const [reminderTime, setReminderTime] = useState('');
  const [icon, setIcon] = useState('target');
  const [vpReward, setVpReward] = useState(5);
  const load = async () => setHabits(await request<Habit[]>('/api/daily-habits'));
  useEffect(() => { void load().catch(() => undefined); }, []);
  const visible = habits.filter((habit) => showArchived ? habit.status === 'archived' : habit.status !== 'archived');
  const active = habits.filter((habit) => habit.status === 'active');
  const completed = active.filter((habit) => habit.completedToday).length;
  const create = async () => { if (!title.trim() || days.length === 0) return; try { await request('/api/daily-habits', { method: 'POST', body: JSON.stringify({ title, daysOfWeek: days, reminderTime: reminderTime || null, icon, vpReward }) }); setTitle(''); setAdding(false); await load(); toast.success('Habit added'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not add habit'); } };
  const toggle = async (habit: Habit) => { try { const result = await request<{ completedToday: boolean; vpAwarded: number }>(`/api/daily-habits/${habit.id}/toggle`, { method: 'POST' }); await load(); if (result.completedToday) toast.success(result.vpAwarded ? `Habit complete · +${result.vpAwarded} VP` : 'Habit complete'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not update habit'); } };
  const status = async (habit: Habit, next: Habit['status']) => { await request(`/api/daily-habits/${habit.id}`, { method: 'PATCH', body: JSON.stringify({ status: next }) }); await load(); };
  const remove = async (habit: Habit) => { if (!window.confirm(`Delete “${habit.title}” and its history?`)) return; await request(`/api/daily-habits/${habit.id}`, { method: 'DELETE' }); await load(); };

  return <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="overflow-hidden rounded-xl border bg-card shadow-sm">
    <header className="flex items-center justify-between border-b bg-muted/30 px-4 py-3"><div className="flex items-center gap-2"><Repeat className="h-4 w-4 text-primary" /><span className="text-sm font-bold">Daily Habits</span>{active.length > 0 && <span className="rounded-md bg-muted px-1.5 py-0.5 text-xs font-black text-muted-foreground">{completed}/{active.length}</span>}</div><div className="flex gap-2"><button onClick={() => setShowArchived((value) => !value)} className="text-xs font-bold text-muted-foreground">{showArchived ? 'Current' : 'Archived'}</button><button onClick={() => setAdding(true)} className="flex items-center gap-1 text-xs font-bold text-primary"><Plus className="h-3.5 w-3.5" />Add</button></div></header>
    {active.length > 0 && <div className="h-1 bg-muted"><motion.div className="h-full bg-primary" animate={{ width: `${completed / active.length * 100}%` }} /></div>}
    <div className="divide-y divide-border/60">{visible.map((habit) => { const Icon = iconMap[habit.icon as keyof typeof iconMap] ?? Target; return <div key={habit.id} className={`group p-3 ${habit.status === 'paused' ? 'opacity-55' : ''}`}><div className="flex items-center gap-3"><button disabled={habit.status !== 'active'} onClick={() => toggle(habit)} className="text-muted-foreground hover:text-primary disabled:cursor-not-allowed">{habit.completedToday ? <CheckCircle2 className="h-5 w-5 fill-primary text-primary" /> : <Circle className="h-5 w-5" />}</button><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{habit.title}</p><div className="mt-1 flex flex-wrap items-center gap-2 text-[10px] font-bold text-muted-foreground"><span>{habit.daysOfWeek.map((day) => weekdays[day]).join(' ')}</span>{habit.reminderTime && <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{habit.reminderTime}</span>}<span className="text-primary">+{habit.vpReward} VP</span></div></div><div className="flex opacity-0 transition-opacity group-hover:opacity-100">{habit.status === 'active' ? <button onClick={() => status(habit, 'paused')} title="Pause" className="p-1.5 text-muted-foreground"><Pause className="h-3.5 w-3.5" /></button> : habit.status === 'paused' ? <button onClick={() => status(habit, 'active')} title="Resume" className="p-1.5 text-muted-foreground"><Play className="h-3.5 w-3.5" /></button> : null}{habit.status !== 'archived' && <button onClick={() => status(habit, 'archived')} title="Archive" className="p-1.5 text-muted-foreground"><Archive className="h-3.5 w-3.5" /></button>}<button onClick={() => remove(habit)} title="Delete" className="p-1.5 text-muted-foreground"><Trash2 className="h-3.5 w-3.5" /></button></div></div>{habit.recentCompletions.length > 0 && <div className="ml-16 mt-2 flex gap-1" title="Recent completion history">{Array.from({ length: 14 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (13-index)); const key = localDateKey(date); return <span key={key} className={`h-2 flex-1 rounded-sm ${habit.recentCompletions.includes(key) ? 'bg-primary' : 'bg-muted'}`} />; })}</div>}</div>; })}{visible.length === 0 && !adding && <p className="p-8 text-center text-sm text-muted-foreground">{showArchived ? 'No archived habits.' : 'Add a habit with the days and reminder that fit your week.'}</p>}</div>
    <AnimatePresence>{adding && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden border-t"><div className="space-y-4 p-4"><input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Habit name" className="w-full rounded-xl border bg-background px-3 py-2 text-sm outline-none focus:border-primary" /><div><p className="mb-2 text-xs font-black uppercase text-muted-foreground">Days</p><div className="flex gap-1.5">{weekdays.map((label, day) => <button key={day} onClick={() => setDays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day].sort())} className={`h-8 w-8 rounded-lg text-xs font-black ${days.includes(day) ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{label}</button>)}</div></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-muted-foreground">Reminder<input type="time" value={reminderTime} onChange={(event) => setReminderTime(event.target.value)} className="mt-1 block w-full rounded-lg border bg-background px-2 py-2 text-foreground" /></label><label className="text-xs font-bold text-muted-foreground">VP reward<input type="number" min={1} max={25} value={vpReward} onChange={(event) => setVpReward(Number(event.target.value))} className="mt-1 block w-full rounded-lg border bg-background px-2 py-2 text-foreground" /></label></div><div><p className="mb-2 text-xs font-black uppercase text-muted-foreground">Icon</p><div className="flex flex-wrap gap-2">{Object.entries(iconMap).map(([name, Icon]) => <button key={name} onClick={() => setIcon(name)} className={`rounded-lg border p-2 ${icon === name ? 'border-primary bg-primary/10 text-primary' : 'text-muted-foreground'}`} title={name}><Icon className="h-4 w-4" /></button>)}</div></div><div className="flex justify-end gap-2"><button onClick={() => setAdding(false)} className="rounded-lg px-3 py-2 text-xs font-bold text-muted-foreground">Cancel</button><button onClick={create} disabled={!title.trim() || days.length === 0} className="rounded-lg bg-primary px-4 py-2 text-xs font-black text-primary-foreground disabled:opacity-40">Create habit</button></div></div></motion.div>}</AnimatePresence>
  </motion.section>;
}
